baseURL = 'https://quint-theme-demo.netlify.app/'
languageCode = 'en-us'
title = 'Joseph Ruan'
theme = "quint"
summaryLength = 20                  # Number of characters in your card summaries

[params]
useToc = true
description = "Joseph Ruan's Portfolio"

[[menus.main]]
name = 'GitHub'
url = 'https://github.com/victoriadrake/hugo-theme-quint'

[markup.goldmark.renderer]
    unsafe = true

# Theme config. Your config (yoursite/hugo.toml) overrides this one.

paginate = 4                        # Number of posts to show on a list page
summaryLength = 20                  # Number of characters in your card summaries
css = ["css/custom.css"]            # Your custom CSS overrides, stored in yoursite/static/
numImages = 10                      # Number of random images to choose from for banners (in themes/quint/static/images)
useToc = false                      # Set to true to show a Table of Contents on multi-heading posts

contact = "You can write me an [email](mailto:me)."

[[params.social]]                 # Customize your social links below!
    url = "https://linkedin.com/in/jlruan"
    icon = "/social/linkedin.png"
    name = "LinkedIn"

[[params.social]]
    url = "https://github.com/jlruan"
    icon = "/social/github.svg"
    name = "GitHub"
