baseURL = 'https://jlruan.me/'
languageCode = 'en-us'
title = 'Joseph Ruan'
theme = "quint"
summaryLength = 20                  # Number of characters in your card summaries


[params]
useToc = true
description = "Joseph Ruan's Portfolio"
paginate = 4                        # Number of posts to show on a list page
css = ["css/custom.css"]            # Your custom CSS overrides, stored in yoursite/static/
numImages = 10                      # Number of random images to choose from for banners (in themes/quint/static/images)

[markup.goldmark.renderer]
    unsafe = true

[[params.social]]                 # Customize your social links below!
    url = "https://jlruan.me/"
    icon = "/social/house.svg"
    name = "Home"

[[params.social]]                 # Customize your social links below!
    url = "https://linkedin.com/in/jlruan"
    icon = "/social/linkedin-2.svg"
    name = "LinkedIn"

[[params.social]]
    url = "https://github.com/jlruan"
    icon = "/social/github.svg"
    name = "GitHub"

[[params.social]]
    url = "/RuanJosephResume.pdf"
    icon = "/social/doc.svg"
    name = "Resume"

[services]
  [services.googleAnalytics]
    id = 'G-Z5R5Y38B1H'

