[build]
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.123.3"
  NODE_VERSION = "19.6.0"
  NPM_VERSION = "9.4.0"

[[headers]]
  for = "/*" # you can configure the correct paths here
  [headers.values]
    access-control-allow-origin = "*" # see a list of allowed values here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin